name: build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode the keystore
        env:
            ENCODED_STRING: ${{ secrets.SIGNING_KEY_BASE64 }}
        run: echo $ENCODED_STRING | base64 -di > "${RUNNER_TEMP}"/keystore.jks
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup gradle
        run: chmod +x gradlew
      - name: Build the project (debug variant)
        run: ./gradlew assembleDebug
      - name: Build the project (release variant)
        run: export RELEASE_STORE_FILE=${RUNNER_TEMP}/keystore.jks && ./gradlew assembleRelease
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: app/build/outputs/apk/
